name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build JAR with Gradle
      run: ./gradlew clean build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t quddnd/myapp:latest .
        docker push quddnd/myapp:latest


  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install Docker Compose on EC2 (if needed)
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        if ! [ -x "$(command -v docker-compose)" ]; then
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        fi
        EOF

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd ~
        docker-compose down
        docker-compose pull
        docker-compose up -d
        EOF

